# Configuración para H2 (Local / Pruebas) - Descomenta estas líneas y comenta las de MySQL para probar sin internet
# spring.datasource.url=jdbc:h2:file:./data/db;DB_CLOSE_DELAY=-1 # URL de la base de datos H2 (archivo local)
# spring.datasource.driver-class-name=org.h2.Driver # Driver de la base de datos H2
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Configuración de MySQL (Aiven)
spring.datasource.url=jdbc:mysql://${MYSQLHOST:club-baloncesto-db-baskect-club.j.aivencloud.com}:${MYSQLPORT:19085}/${MYSQLDATABASE:club_baloncesto}?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useServerPrepStmts=true&enabledTLSProtocols=TLSv1.2,TLSv1.3
spring.datasource.username=${MYSQLUSER:avnadmin}
spring.datasource.password=${MYSQLPASSWORD:AVNS_J700JdboO98TNUjTtXB}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# CONFIGURACIÓN DEL POOL DE CONEXIONES (HikariCP)
# Número máximo de conexiones reales que se mantendrán abiertas en el pool
spring.datasource.hikari.maximum-pool-size=10 
# Tiempo mínimo que una conexión puede estar inactiva en el pool antes de ser retirada (en milisegundos)
spring.datasource.hikari.idle-timeout=30000 
# Tiempo máximo que el pool esperará por una conexión disponible antes de lanzar un error (en milisegundos)
spring.datasource.hikari.connection-timeout=20000 
# Tiempo de vida máximo de una conexión en el pool (en milisegundos)
spring.datasource.hikari.max-lifetime=1800000 

# JPA / Hibernate
# Estrategia de creación/actualización del esquema de la base de datos
spring.jpa.hibernate.ddl-auto=update 
# Muestra las sentencias SQL generadas por Hibernate en la consola
spring.jpa.show-sql=true 

# Permitir que SwingUI y LoginUI se referencien mutuamente
# Permite referencias circulares entre beans de Spring, útil para la UI de Swing
spring.main.allow-circular-references=true 